<a href="https://colab.research.google.com/github/PrathmeshPawarb/Data-Science-Machine-Learning-Assignments/blob/main/Random_Forest_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv('/content/Company_Data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [ ]:
df.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [ ]:
print(df['Sales'].min())
print(df['Sales'].mean())
print(df['Sales'].max())

0.0
7.496325000000001
16.27


In [ ]:
#converting Sales Contineous data into Sales categorial data

df['Ssales'] = pd.cut(x=df['Sales'], bins=[ 0,5,10,20],labels=['Bad_Sales','Ok_Sales','Good_Sales'])

# dropping Sales column
df.drop('Sales', axis=1, inplace=True)

df.head()

CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0        138      73           11         276    120       Bad   42   
1        111      48           16         260     83      Good   65   
2        113      35           10         269     80    Medium   59   
3        117     100            4         466     97    Medium   55   
4        141      64            3         340    128       Bad   38   

   Education Urban   US      Ssales  
0         17   Yes  Yes    Ok_Sales  
1         10   Yes  Yes  Good_Sales  
2         12   Yes  Yes  Good_Sales  
3         14   Yes  Yes    Ok_Sales  
4         13   Yes   No   Bad_Sales

In [ ]:
df['Ssales'].unique()

['Ok_Sales', 'Good_Sales', 'Bad_Sales', NaN]
Categories (3, object): ['Bad_Sales' < 'Ok_Sales' < 'Good_Sales']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
df['ShelveLoc']=le.fit_transform(df['ShelveLoc'])
df['Urban']=le.fit_transform(df['Urban'])
df['US']=le.fit_transform(df['US'])
df['Ssales']=le.fit_transform(df['Ssales'])

df.head()

CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        138      73           11         276    120          0   42   
1        111      48           16         260     83          1   65   
2        113      35           10         269     80          2   59   
3        117     100            4         466     97          2   55   
4        141      64            3         340    128          0   38   

   Education  Urban  US  Ssales  
0         17      1   1       2  
1         10      1   1       1  
2         12      1   1       1  
3         14      1   1       2  
4         13      1   0       0

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
# Picking LogisticRegression as base model

from sklearn.linear_model import LogisticRegression
m1 = LogisticRegression()

In [ ]:
# fitting base model in BaggingClassifier

from sklearn.ensemble import BaggingClassifier
model1 = BaggingClassifier(base_estimator= m1, n_estimators=50,random_state=5)

In [ ]:
# cross_val_score

from sklearn.model_selection import cross_val_score
score1 = cross_val_score(model1, x, y, cv = 10)

score1

array([0.575, 0.65 , 0.65 , 0.7  , 0.75 , 0.675, 0.7  , 0.65 , 0.65 ,
       0.725])

In [ ]:
score1.mean()

0.6725000000000001

In [ ]:
# Boosting - AdaBoostClassifier

from sklearn.ensemble import AdaBoostClassifier
ad = AdaBoostClassifier(n_estimators= 50,random_state=5)

In [ ]:
score2 = cross_val_score(ad, x,y,cv=10)

In [ ]:
score2.mean()

0.5725000000000001

In [ ]:
# Bagging - RandomForestClassifier

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(criterion = "entropy",n_estimators=50,max_features=3)

In [ ]:
# cross_val_score


score3 = cross_val_score(rf,x,y,cv = 10)

score3

array([0.7  , 0.725, 0.725, 0.675, 0.725, 0.775, 0.675, 0.65 , 0.625,
       0.65 ])

In [ ]:
score3.mean()

0.6925000000000001

Random forest(uses decision tree as base model) give batter accuracy than Adaboost and logisticregression model

#Fraud Check

In [ ]:
df2 = pd.read_csv('/content/Fraud_check.csv')
df2.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Undergrad        600 non-null    int64
 1   Marital.Status   600 non-null    int64
 2   Taxable.Income   600 non-null    int64
 3   City.Population  600 non-null    int64
 4   Work.Experience  600 non-null    int64
 5   Urban            600 non-null    int64
dtypes: int64(6)
memory usage: 28.2 KB


In [ ]:
df2['Undergrad'] = le.fit_transform(df2['Undergrad'])
df2['Marital.Status'] = le.fit_transform(df2['Marital.Status'])
df2['Urban'] = le.fit_transform(df2['Urban'])

df2.head()

Undergrad  Marital.Status  Taxable.Income  City.Population  \
0          0               2           68833            50047   
1          1               0           33700           134075   
2          0               1           36925           160205   
3          1               2           50190           193264   
4          0               1           81002            27533   

   Work.Experience  Urban  
0               10      1  
1               18      1  
2               30      1  
3               15      1  
4               28      0

In [ ]:
#seperate dependent and independent fectures

x1= df2.iloc[:,:]
y1= df2['Taxable.Income'].apply(lambda X: "Risky" if X <= 30000 else "Good")

# using lambda function to define condition

In [ ]:
# Boosting - AdaBoostClassifier

from sklearn.ensemble import AdaBoostClassifier
ad = AdaBoostClassifier(n_estimators= 50,random_state=5)

In [ ]:
scoreA = cross_val_score(ad, x1,y1,cv=5)
scoreA

array([1.        , 0.99166667, 1.        , 1.        , 1.        ])

In [ ]:
scoreA.mean()

0.9983333333333334

In [ ]:
# Bagging - RandomForestClassifier

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(criterion = "entropy",n_estimators=50,max_features=3)

In [ ]:
# cross_val_score


scoreB = cross_val_score(rf,x1,y1,cv = 5)

scoreB

array([1.        , 0.99166667, 1.        , 1.        , 1.        ])

In [ ]:
scoreB.mean()

0.9983333333333334